async page => {
    const base='http://127.0.0.1:5101';
    if(!page.url().startsWith(base+'/'))throw new Error('Use the disposable preview.');
    const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.request.post(base+'/__test/user/1');
    await page.request.post(base+'/__test/research-delay',{data:{seconds:2}});
    await page.setViewportSize({width:1440,height:1100});
    await page.goto(base+'/crm/prospecting');
    await page.evaluate(()=>sessionStorage.clear());
    await page.locator('#prospect-import').click();
    await page.locator('#prospect-upload-form input[type=file]').setInputFiles('dashboard_html/tests/fixtures/prospecting_evidence.csv');
    await page.getByRole('button',{name:'Preview file',exact:true}).click();
    await page.locator('#prospect-preview:not([hidden])').waitFor();
    await page.getByRole('button',{name:'Create prospect list',exact:true}).click();
    await page.waitForURL(/prospecting\/[0-9]+/);
    await page.locator('#prospect-enrich').click();
    await page.waitForFunction(()=>document.getElementById('research-picked-count').textContent==='2 selected');
    await page.locator('[name=research-mode][value=advanced]').check();await page.locator('#research-start').click();
    await page.waitForFunction(()=>document.querySelectorAll('#research-activity-body li').length>2);
    await page.locator('.research-activity>summary').click();
    assert((await page.locator('#research-activity-body').innerText()).includes('Existing records'),'Internal activity recorded');
    await page.screenshot({path:'/tmp/research-live-activity.png'});
    await page.waitForFunction(()=>document.querySelector('.research-status-pill')?.textContent==='Research complete');
    assert((await page.locator('#research-activity-body').innerText()).includes('Source returned data'),'Source returns recorded');
    assert(await page.locator('#research-detail .research-group').count()===2,'Each parcel has its own group');
    assert((await page.locator('#research-detail .research-group').first().innerText()).includes('Recorded roles'),'Record categories grouped');
    const tax=page.locator('.research-finding').filter({hasText:'Historical lien-sale notice entries'}).first();
    await page.locator('.research-category').filter({hasText:'Lien-sale notices'}).first().locator(':scope > summary').click();
    await tax.locator('.research-evidence summary').click();
    assert((await tax.innerText()).includes('December 2017'),'Literal notice excerpt visible');
    assert((await tax.innerText()).includes('personal liability'),'Limitations distinguish property from person');
    await page.screenshot({path:'/tmp/research-grouped-evidence.png'});
    await page.locator('.research-activity>summary').click();
    await page.locator('#research-detail').evaluate(el=>el.scrollTop=0);
    await page.locator('.research-review').scrollIntoViewIfNeeded();
    await page.screenshot({path:'/tmp/research-evidence-overview.png'});
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>document.documentElement.setAttribute('data-crm-theme','dark'));
    assert(await page.locator('#research-detail').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'Evidence fits mobile');
    await page.screenshot({path:'/tmp/research-evidence-mobile.png'});
    await page.locator('#research-new').click();
    await page.locator('#research-start').click();
    await page.waitForFunction(()=>document.querySelectorAll('.research-active-row').length>0);
    await page.locator('#research-detail').scrollIntoViewIfNeeded();
    assert(await page.locator('#prospect-enrichment-cancel').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),'Cancel stays accessible');
    await page.locator('#prospect-enrichment-cancel').click();
    await page.waitForFunction(()=>document.querySelector('.research-status-pill')?.textContent==='Run stopped');
    if(!await page.locator('.research-activity').evaluate(el=>el.open))await page.locator('.research-activity>summary').click();
    assert((await page.locator('#research-activity-body').innerText()).includes('Cancelled by requester'),'Cancellation recorded');
    await page.reload();await page.locator('#prospect-enrich').click();
    await page.waitForFunction(()=>document.querySelector('.research-status-pill')?.textContent==='Run stopped');
    await page.locator('.research-activity>summary').click();
    assert((await page.locator('#research-activity-body').innerText()).includes('Cancelled by requester'),'Cancellation log survives navigation');
    assert(!errors.length,errors.join('; '));
    return 'PASS: parcel/category grouping, source evidence and limits, live durable activity, fixed cancel, cancellation persistence, mobile dark evidence';
}
