// Real local APIs and browser interactions, with isolated synthetic fixture data.
async page => {
    const base='http://127.0.0.1:5101';
    if(!page.url().startsWith(base+'/'))throw new Error('Use the disposable local preview.');
    const assert=(ok,message)=>{if(!ok)throw new Error(message);};
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const saved=()=>page.waitForFunction(()=>document.getElementById('prospect-layout-status').textContent==='Layout saved');
    const waitRows=n=>page.waitForFunction(n=>document.querySelectorAll('#prospect-rows tr[data-row]').length===n,n);
    const close=id=>page.locator(`#${id} [data-close]`).click();
    await page.request.post(base+'/__test/user/1');
    await page.setViewportSize({width:1440,height:1100});await page.emulateMedia({colorScheme:'light'});
    await page.goto(base+'/crm/prospecting');
    await page.getByRole('button',{name:'Import CSV',exact:true}).click();
    await page.locator('#prospect-upload-form input[type=file]').setInputFiles('dashboard_html/tests/fixtures/prospecting.csv');
    await page.getByRole('button',{name:'Preview file',exact:true}).click();
    await page.locator('#prospect-preview:not([hidden])').waitFor();
    await page.getByRole('button',{name:'Create prospect list',exact:true}).click();
    await page.waitForURL(/prospecting\/[0-9]+$/);await waitRows(2);const listUrl=page.url();
    await page.locator('#prospect-select-page').check();
    assert((await page.locator('#prospect-selection-count').innerText()).includes('2 selected'),'Page selection');
    await page.locator('#prospect-bulk-edit').click();
    await page.locator('#prospect-bulk-form [name=status]').selectOption('interested');
    await page.locator('#prospect-bulk-form [name=follow_action]').selectOption('set');
    await page.locator('#prospect-bulk-form [name=next_follow_up]').fill('2026-12-01');
    await page.locator('#prospect-bulk-confirm').click();
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-status]')].every(el=>el.value==='interested'));
    await page.locator('#prospect-undo').click();
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-status]')].every(el=>el.value==='new'));
    await page.locator('[data-select-row]').first().check();await page.locator('#prospect-bulk-archive').click();await page.locator('#prospect-bulk-confirm').click();await waitRows(1);
    await page.locator('#prospect-filters [name=archived]').selectOption('archived');await page.getByRole('button',{name:'Apply',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#prospect-rows').textContent.includes('Test Person'));
    await page.locator('#prospect-select-page').check();await page.locator('#prospect-bulk-restore').click();await page.locator('#prospect-bulk-confirm').click();await waitRows(0);
    await page.locator('#prospect-filters [name=archived]').selectOption('active');await page.getByRole('button',{name:'Apply',exact:true}).click();await waitRows(2);
    await page.locator('#prospect-add-person').click();
    await page.locator('#prospect-person-fields [name=c0]').fill('Manual Person');await page.locator('#prospect-person-fields [name=c1]').fill('Example Co');
    await page.locator('#prospect-person-form button[type=submit]').click();await waitRows(3);
    await page.locator('#prospect-append-csv').click();await page.locator('#prospect-append-upload [type=file]').setInputFiles('dashboard_html/tests/fixtures/prospecting_append.csv');
    await page.getByRole('button',{name:'Preview additions',exact:true}).click();await page.locator('#prospect-append-preview:not([hidden])').waitFor();
    assert(await page.locator('#prospect-append-mapping [name=c0]').inputValue()==='c3','Append email mapped by header');
    assert(await page.locator('#prospect-append-mapping [name=c4]').inputValue()==='new','New incoming column preserved');
    await page.getByRole('button',{name:'Add rows to this list',exact:true}).click();await waitRows(4);
    await page.locator('#prospect-check-duplicates').click();await page.locator('#prospect-duplicates-dialog[open]').waitFor();
    assert((await page.locator('#prospect-duplicate-summary').innerText()).includes('2 leads'),'Shared-phone duplicates found after append');
    await close('prospect-duplicates-dialog');
    await page.locator('.prospect-duplicate-badge').first().click();
    assert((await page.locator('#prospect-duplicates-body').innerText()).includes('phone'),'Match explains reason');await close('prospect-duplicates-dialog');
    await page.locator('.prospect-columns summary').click();await page.locator('#prospect-add-column').click();
    await page.locator('#prospect-column-form [name=label]').fill('Outreach priority');await page.locator('#prospect-column-form button[type=submit]').click();
    await page.locator('#prospect-column-dialog').waitFor({state:'hidden'});await saved();
    await page.locator('[data-column-settings=c7]').click();await page.locator('#prospect-column-form [name=label]').fill('Priority notes');
    await page.locator('#prospect-column-form [name=width]').fill('280');await page.locator('#prospect-column-form [name=pinned]').check();
    await page.locator('#prospect-column-form button[type=submit]').click();await page.locator('#prospect-column-dialog').waitFor({state:'hidden'});await saved();
    await page.reload();await waitRows(4);
    assert(await page.locator('#prospect-head [data-column=c7]').evaluate(el=>Math.round(el.getBoundingClientRect().width))===280,'Width restored');
    assert(await page.locator('#prospect-head [data-column=c7]').evaluate(el=>el.classList.contains('prospect-pinned')),'Pin restored');
    await page.locator('[data-resize=c7]').focus();await page.keyboard.press('ArrowRight');await saved();
    await page.waitForFunction(()=>Math.round(document.querySelector('#prospect-head [data-column=c7]').getBoundingClientRect().width)===290);
    // A failed cell save must not disappear when selecting the entire page.
    await page.route('**/api/rows/*',route=>route.request().method()==='PATCH'?route.fulfill({status:500,contentType:'application/json',body:'{"error":"Test edit failure"}'}):route.continue());
    await page.locator('#prospect-rows [data-cell=c2]').first().click();await page.locator('#prospect-rows textarea').fill('Unsaved draft');
    await page.locator('#prospect-select-page').check();
    await page.waitForFunction(()=>document.querySelector('#prospect-message').textContent.includes('Test edit failure'));
    assert(await page.locator('#prospect-rows textarea').inputValue()==='Unsaved draft','Failed draft retained during select all');
    await page.unroute('**/api/rows/*');await page.locator('#prospect-rows textarea').press('Escape');
    // Quoted tabular clipboard data is previewed and applied to displayed editable columns.
    await page.context().grantPermissions(['clipboard-read','clipboard-write']);
    await page.evaluate(()=>navigator.clipboard.writeText('212-555-0190\tfirst@example.test\n212-555-0191\tsecond@example.test'));
    await page.locator('#prospect-rows [data-cell=c2]').first().click();
    await page.keyboard.press('ControlOrMeta+V');
    await page.locator('#prospect-bulk-dialog[open]').waitFor();
    assert((await page.locator('#prospect-bulk-description').innerText()).includes('4 cells across 2 rows'),'Paste previews affected range');
    await page.locator('#prospect-bulk-confirm').click();await page.waitForFunction(()=>document.querySelector('#prospect-rows [data-cell=c2]').textContent==='212-555-0190');
    await page.locator('#prospect-undo').click();await page.waitForFunction(()=>document.querySelector('#prospect-rows [data-cell=c2]').textContent==='212-555-0100');
    await page.locator('[data-network-view=company]').click();await page.locator('.prospect-network-card').first().waitFor();
    const company=page.locator('.prospect-network-card').filter({hasText:'Example Co'});await company.click();
    assert((await page.locator('#prospect-profile-body').innerText()).includes('People · 3'),'Company groups three people');
    await close('prospect-profile-dialog');await page.locator('#prospect-new-profile').click();
    await page.locator('#prospect-profile-form [name=kind]').selectOption('building');await page.locator('#prospect-profile-form [name=name]').fill('123 Main St');
    await page.locator('#prospect-profile-form [name=address]').fill('123 Main St, Brooklyn, NY');await page.locator('#prospect-profile-form [name=notes]').fill('Lobby access control opportunity');
    await page.locator('#prospect-profile-form button[type=submit]').click();await page.locator('#prospect-profile-dialog[open]').waitFor();
    await page.locator('.prospect-link-editor').first().evaluate(el=>el.open=true);
    const sourceOption=await page.locator('#prospect-link-form [name=source_id] option').filter({hasText:'Example Co · Company'}).getAttribute('value');
    await page.locator('#prospect-link-form [name=source_id]').selectOption(sourceOption);await page.locator('#prospect-link-form [name=relation]').selectOption('manages');
    const buildingOption=await page.locator('#prospect-link-form [name=target_id] option').filter({hasText:'123 Main St · Building'}).getAttribute('value');
    await page.locator('#prospect-link-form [name=target_id]').selectOption(buildingOption);await page.locator('#prospect-link-form [name=note]').fill('Confirmed with property manager');
    await page.locator('#prospect-link-form button[type=submit]').click();await page.getByRole('heading',{name:'People at managing companies',exact:true}).waitFor();
    assert((await page.locator('#prospect-profile-body').innerText()).includes('Manual Person'),'Building reaches people through management company');
    await page.locator('#prospect-profile-body [data-open-profile]').filter({hasText:'Example Co'}).click();
    assert((await page.locator('#prospect-profile-body').innerText()).includes('Buildings · 1'),'Company shows managed building');
    await close('prospect-profile-dialog');await page.locator('[data-network-view=building]').click();await page.locator('.prospect-network-card').filter({hasText:'123 Main St'}).waitFor();
    await page.screenshot({path:'/tmp/prospecting-buildings-desktop.png',fullPage:true});
    await page.locator('[data-network-view=people]').click();await page.locator('#prospect-select-page').check();await page.locator('#prospect-bulk-review').click();
    await page.locator('#prospect-review-queue:not([hidden])').waitFor();assert((await page.locator('#prospect-review-progress').innerText()).includes('1 of 4'),'CRM review queue');
    await page.locator('#prospect-review-next').click();await page.waitForFunction(()=>document.querySelector('#prospect-review-progress').textContent.includes('2 of 4'));await close('prospect-lead-dialog');
    await page.locator('#prospect-clear-selection').click();
    // Explicit linking reuses a chosen CRM contact when the second lead is promoted.
    await page.locator('[data-open]').filter({hasText:'Test Person'}).click();
    await page.getByText('Ready for CRM? Review & add contact',{exact:true}).click();
    await page.getByRole('button',{name:'Add to CRM',exact:true}).click();
    await page.getByRole('link',{name:'Open CRM contact',exact:true}).waitFor();
    const crmHref=await page.getByRole('link',{name:'Open CRM contact',exact:true}).getAttribute('href');
    await close('prospect-lead-dialog');
    await page.locator('[data-open]').filter({hasText:'Manual Person'}).click();
    await page.locator('[data-profile-row]').click();await page.locator('#prospect-profile-dialog[open]').waitFor();
    await page.locator('#prospect-crm-reference summary').click();
    await page.locator('#prospect-crm-search [name=q]').fill('Test Person');await page.locator('#prospect-crm-search button').click();
    await page.locator('#prospect-crm-link:not([hidden])').waitFor();await page.locator('#prospect-crm-link button').click();
    await page.locator('#prospect-profile-body a').filter({hasText:'Open CRM contact'}).waitFor();
    await page.locator('[data-open-profile-lead]').click();
    await page.getByText('Ready for CRM? Review & add contact',{exact:true}).click();await page.getByRole('button',{name:'Add to CRM',exact:true}).click();
    await page.getByRole('link',{name:'Open CRM contact',exact:true}).waitFor();
    assert(await page.getByRole('link',{name:'Open CRM contact',exact:true}).getAttribute('href')===crmHref,'Promotion reuses explicit CRM reference');
    await close('prospect-lead-dialog');
    await page.setViewportSize({width:375,height:812});await page.emulateMedia({colorScheme:'dark'});await page.reload();await waitRows(4);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile viewport fits');
    await page.locator('.prospect-columns summary').click();
    const menu=await page.locator('.prospect-columns-panel').boundingBox();assert(menu.x>=0 && menu.x+menu.width<=375,'Mobile column controls fit');await page.locator('.prospect-columns summary').click();
    await page.locator('[data-network-view=building]').click();await page.locator('.prospect-network-card').first().click();
    assert(await page.locator('#prospect-profile-dialog').evaluate(el=>el.getBoundingClientRect().width<innerWidth),'Mobile profile fits');
    await page.screenshot({path:'/tmp/prospecting-profile-mobile.png'});await close('prospect-profile-dialog');
    assert(errors.length===0,errors.join('; '));
    return {passed:true,url:listUrl,checks:'Bulk update/undo/archive/restore, manual add, append CSV mapping, duplicates, add/rename/pin/resize columns, paste/undo, company/building relationships, indirect contacts, CRM review queue, mobile dark mode'};
}
