// Uses only the disposable local preview, including its test-only identity switch.
async page => {
    const base='http://127.0.0.1:5101';
    if (!page.url().startsWith(base+'/')) throw new Error('Use the disposable preview.');
    const assert=(ok,message)=>{if(!ok)throw new Error(message);};
    const asUser=async id=>{await page.request.post(`${base}/__test/user/${id}`);};
    await asUser(1);
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(base+'/crm/prospecting');
    await page.getByRole('button',{name:'Import CSV',exact:true}).click();
    await page.locator('#prospect-upload-form input[type=file]').setInputFiles('dashboard_html/tests/fixtures/prospecting.csv');
    await page.getByRole('button',{name:'Preview file',exact:true}).click();
    await page.locator('#prospect-preview:not([hidden])').waitFor();
    assert(await page.locator('#prospect-import-owner').inputValue()==='1','Admin import defaults to me');
    await page.locator('#prospect-import-owner').selectOption('2');
    await page.getByRole('button',{name:'Create prospect list',exact:true}).click();
    await page.waitForURL(/prospecting\/[0-9]+$/);
    await page.locator('[data-open]').first().waitFor();
    const url=page.url(),id=Number(url.split('/').pop());
    assert((await page.locator('#prospect-owner-label').innerText()).includes('Assigned to Alex'),'Import assigned to teammate');
    await asUser(2);await page.goto(url);
    await page.locator('[data-open]').first().waitFor();
    assert(await page.locator('#prospect-assignment-form').count()===0,'Member cannot reassign from UI');
    await page.locator('[data-open]').first().click();
    await page.locator('#prospect-notes-form textarea').fill('Alex researched this lead');
    await page.getByRole('button',{name:'Save notes & status',exact:true}).click();
    await page.waitForFunction(()=>document.getElementById('prospect-message').textContent==='Notes and status saved.');
    await page.locator('#prospect-lead-dialog [data-close]').click();
    const forbidden=await page.evaluate(async id=>(await fetch(`/crm/prospecting/api/lists/${id}/assignment`,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-Token':window.PROSPECT_CONFIG.csrf},body:JSON.stringify({assigned_to_id:3,version:1})})).status,id);
    assert(forbidden===403,'Member cannot forge assignment API');
    await page.getByRole('button',{name:'Import CSV',exact:true}).click();
    assert(await page.locator('#prospect-import-owner').count()===0,'Member has no import assignee selector');
    await page.locator('#prospect-import-dialog [data-close]').click();
    await asUser(3);await page.goto(base+'/crm/prospecting');
    await page.waitForFunction(()=>document.querySelector('#prospect-lists').textContent.length>0);
    assert(await page.locator(`a[href="/crm/prospecting/${id}"]`).count()===0,'Other member cannot list it');
    assert((await page.request.get(url)).status()===404,'Other member cannot open it');
    await asUser(1);await page.goto(url);
    await page.locator('#prospect-assignment-form select').selectOption('3');
    await page.getByRole('button',{name:'Save assignment',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#prospect-owner-label').textContent.includes('Assigned to Sam'));
    await asUser(2);
    assert((await page.request.get(url)).status()===404,'Former owner loses page access');
    assert((await page.request.get(url+'/export.csv')).status()===404,'Former owner loses export access');
    await asUser(3);await page.goto(url);
    await page.locator('[data-open]').first().click();
    assert(await page.locator('#prospect-notes-form textarea').inputValue()==='Alex researched this lead','Research survives reassignment');
    await page.locator('#prospect-lead-dialog [data-close]').click();
    await asUser(1);await page.goto(url);
    await page.locator('#prospect-assignment-form select').selectOption('1');
    await page.getByRole('button',{name:'Save assignment',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#prospect-owner-label').textContent.includes('Assigned to Me'));
    await page.goto(base+'/crm/prospecting');
    await page.locator('#prospect-owner-filter').selectOption('1');
    assert(await page.locator(`a[href="/crm/prospecting/${id}"]`).count()===1,'Admin can filter their own sheets');
    await page.locator('#prospect-owner-filter').selectOption('2');
    assert(await page.locator(`a[href="/crm/prospecting/${id}"]`).count()===0,'Owner filter excludes other sheets');
    await page.goto(url);await page.locator('#prospect-assignment-form').waitFor();
    await page.setViewportSize({width:375,height:812});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Assignment controls fit mobile');
    return {passed:true,checks:'Admin import for self/team, member isolation, forged assignment rejection, reassignment to another member/self, retained notes, owner filter, mobile layout'};
}
