async page => {
    const base='http://127.0.0.1:5101';
    if(!page.url().startsWith(base+'/'))throw new Error('Use the disposable local preview.');
    const assert=(ok,message)=>{if(!ok)throw new Error(message);};
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.request.post(base+'/__test/user/1');
    await page.request.post(base+'/__test/research-delay',{data:{seconds:4}});
    await page.setViewportSize({width:1440,height:1100});
    await page.goto(base+'/crm/prospecting');
    await page.evaluate(()=>document.documentElement.setAttribute('data-crm-theme','light'));
    await page.locator('#prospect-import').click();
    await page.locator('#prospect-upload-form input[type=file]').setInputFiles('dashboard_html/tests/fixtures/prospecting_research.csv');
    await page.getByRole('button',{name:'Preview file',exact:true}).click();
    await page.locator('#prospect-preview:not([hidden])').waitFor();
    await page.getByRole('button',{name:'Create prospect list',exact:true}).click();
    await page.waitForURL(/prospecting\/[0-9]+/);
    const listUrl=page.url(), listId=Number(listUrl.match(/prospecting\/(\d+)/)[1]);
    await page.locator('#prospect-enrich').click();
    await page.locator('#research-setup:not([hidden])').waitFor();
    await page.waitForFunction(()=>document.getElementById('research-picked-count').textContent==='2 selected');
    await page.locator('#research-pick-none').click();
    assert(await page.locator('#research-start').isDisabled(),'Empty selection cannot start');
    await page.locator('#research-search').fill('Jane');
    await page.locator('#research-pick-all').click();
    assert((await page.locator('#research-picked-count').innerText()).includes('1 selected'),'Select search matches');
    await page.locator('#research-search').fill('');await page.locator('#research-pick-all').click();
    await page.screenshot({path:'/tmp/research-setup-desktop.png'});
    await page.locator('[name=research-mode][value=advanced]').check();
    await page.locator('#research-start').click();
    await page.locator('#research-run:not([hidden])').waitFor();
    await page.waitForFunction(()=>document.querySelectorAll('.research-active-row').length===2);
    await page.screenshot({path:'/tmp/research-running-desktop.png'});
    assert((await page.locator('#prospect-enrichment-summary').innerText()).includes('2 running in parallel'),'Parallel work visible');
    await page.locator('#prospect-enrichment-dialog [data-close]').click();
    await page.waitForFunction(()=>document.getElementById('prospect-message').textContent.includes('still running'));
    await page.goto(base+'/crm/prospecting');
    await page.locator('.research-inbox-card').first().waitFor();
    await page.locator('.research-inbox-card').first().click();
    await page.locator('#research-run:not([hidden])').waitFor();
    await page.waitForFunction(()=>document.querySelector('.research-status-pill')?.textContent==='Research complete');
    await page.locator('[data-research-view=ready]').click();
    await page.locator('.research-finding').first().waitFor();
    assert((await page.locator('#research-detail').innerText()).includes('Registered Agent'),'Agent role retained');
    assert(await page.locator('#research-detail input[type=checkbox]:checked').count()===2,'Clear findings preselected');
    await page.locator('#research-detail input[type=checkbox]').last().uncheck();
    await page.locator('#prospect-enrichment-dialog [data-close]').click();
    await page.reload();await page.locator('#prospect-enrich').click();
    await page.locator('.research-finding').first().waitFor();
    assert(await page.locator('#research-detail input[type=checkbox]:checked').count()===1,'Checkbox choices survive reload');
    await page.locator('#prospect-enrichment-approve').click();
    await page.waitForFunction(()=>document.querySelector('#research-detail .research-kicker')?.textContent.includes('REVIEWED'));
    const rows=await (await page.request.get(base+`/crm/prospecting/api/lists/${listId}`)).json();
    assert(rows.rows[0].research.length===1 && rows.rows[0].research[0].label==='Registered company','Only selected finding saved');
    assert(rows.rows[0].notes==='' && !rows.rows[0].promoted_at,'Research stays separate from notes and CRM');
    await page.locator('#prospect-enrichment-dialog [data-close]').click();
    await page.evaluate(id=>window.ProspectSheet.openLead(id),rows.rows[0].id);
    await page.locator('.prospect-approved-research summary').click();
    assert(await page.locator('.prospect-approved-research a').getAttribute('href')==='https://apps.dos.ny.gov/publicInquiry/','Source retained');
    await page.locator('#prospect-lead-dialog [data-close]').click();
    await page.locator('#prospect-undo').click();
    await page.waitForFunction(()=>document.getElementById('prospect-message').textContent.includes('undone'));
    await page.locator('[data-select-row]').first().check();await page.locator('#prospect-bulk-enrich').click();
    await page.waitForFunction(()=>!document.getElementById('research-setup').hidden && document.getElementById('research-picked-count').textContent==='1 selected');
    await page.request.post(base+'/__test/research-delay',{data:{seconds:0}});
    await page.locator('[name=research-mode][value=advanced]').check();await page.locator('#research-start').click();
    await page.waitForFunction(()=>document.querySelector('.research-status-pill')?.textContent==='Research complete' && !document.getElementById('prospect-enrichment-approve-run').disabled);
    await page.locator('.research-bulk>summary').click();await page.locator('#prospect-enrichment-approve-run').click();
    await page.waitForFunction(()=>document.querySelector('#research-detail .research-kicker')?.textContent.includes('REVIEWED'));
    const approved=await (await page.request.get(base+`/crm/prospecting/api/lists/${listId}`)).json();
    assert(approved.rows[0].research.length===2,'Whole-run approval applies default findings');
    await page.screenshot({path:'/tmp/research-review-desktop.png'});
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>document.documentElement.setAttribute('data-crm-theme','dark'));
    assert(await page.locator('#prospect-enrichment-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'Mobile has no page overflow');
    await page.screenshot({path:'/tmp/research-review-mobile-dark.png'});
    await page.locator('#research-new').click();await page.locator('#research-setup:not([hidden])').waitFor();
    assert(await page.locator('.research-main').evaluate(el=>el.scrollTop)===0,'New research starts at top');
    assert(await page.locator('#prospect-enrichment-dialog').evaluate(el=>el.clientWidth===innerWidth),'Mobile workspace fills viewport');
    await page.screenshot({path:'/tmp/research-setup-mobile-dark.png'});
    assert(!errors.length,errors.join('; '));
    return 'PASS: searchable selection, parallel source progress, close/navigate/resume, persistent choices, review filters, selective approval, undo, bulk approval, desktop/light and mobile/dark';
}
